export const sisterQuotes = [
    { quote: "A sister is both your mirror and your opposite.", author: "Elizabeth Fishel" },
    { quote: "A sister is a little bit of childhood that can never be lost.", author: "Marion C. Garretty" },
    { quote: "Sisters are different flowers from the same garden.", author: "Unknown" },
    { quote: "Having a sister is like having a best friend you can’t get rid of.", author: "Amy Li" },
    { quote: "Sisters may drive you crazy, get into your stuff, and irritate you. But if anyone else dares say so, a sister will defend you to the death.", author: "Unknown" },
    { quote: "A sister is someone who knows you better than yourself.", author: "Unknown" },
    { quote: "Side by side or miles apart, sisters will always be connected by heart.", author: "Unknown" },
    { quote: "Sisters are different chocolates from the same box.", author: "Unknown" },
    { quote: "Sisters are like stars. You may not always see them, but you know they’re always there.", author: "Unknown" },
    { quote: "Sisters are the perfect best friends.", author: "Unknown" },
    { quote: "A sister’s love is forever, no matter the distance.", author: "Unknown" },
    { quote: "A sister shares childhood memories and grown-up dreams.", author: "Unknown" },
    { quote: "What’s the good of news if you haven’t a sister to share it?", author: "James DeVries" },
    { quote: "A loyal sister is worth a thousand friends.", author: "Unknown" },
    { quote: "Sisters teach us about cooperation, fairness, caring, and kindness.", author: "Unknown" },
    { quote: "Sisters are like glue. They keep the family together.", author: "Unknown" },
    { quote: "Sisters help make the hard times easier and the easy times more fun.", author: "Unknown" },
    { quote: "Sisters don’t need words. They have perfected their own secret language of smiles, sighs, gasps, winks, and eye rolls.", author: "Unknown" },
    { quote: "An older sister is a friend and defender—a listener, conspirator, a counselor, and a sharer of delights.", author: "Pam Brown" },
    { quote: "A sister is a gift to the heart, a friend to the spirit, a golden thread to the meaning of life.", author: "Isadora James" },
    { quote: "Sisters are angels who lift us up when our wings forget how to fly.", author: "Unknown" },
    { quote: "Sisters are for sharing laughter and wiping tears.", author: "Unknown" },
    { quote: "Sisters are the people we practice on, the ones who teach us about fairness and cooperation and kindness and caring.", author: "Pamela Dugdale" },
    { quote: "Big sisters are the crabgrass in the lawn of life.", author: "Charles M. Schulz" },
    { quote: "Sweet is the voice of a sister in the season of sorrow.", author: "Benjamin Disraeli" },
    { quote: "There is no better friend than a sister. And there is no better sister than you.", author: "Unknown" },
    { quote: "Sisters function as safety nets in a chaotic world simply by being there for each other.", author: "Carol Saline" },
    { quote: "Sisters are different shades of the same color.", author: "Unknown" },
    { quote: "My sister is my hero. She stands by me when no one else does.", author: "Unknown" },
    { quote: "The best thing about having a sister was that I always had a friend.", author: "Cali Rae Turner" }
  ];
